apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacman-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacman-node-reader
subjects:
  - kind: ServiceAccount
    name: pacman
    namespace: default
roleRef:
  kind: ClusterRole
  name: pacman-node-reader
  apiGroup: rbac.authorization.k8s.io
